services:
  - type: web
    name: point-matrix
    runtime: static
    rootDir: dashboard
    buildCommand: git lfs pull --include="dashboard/public/frames/**" && npm ci && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
